import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { connectWallet } from "@/walletActions";
import { useState } from "react";
import { buy } from "@/contractServices";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [walletAddress, setwalletAddress] = useState("");
  async function ConnectWallet() {
    const userAddress = await connectWallet(true);
    setwalletAddress(userAddress);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>Connect Wallet</div>
        <button onClick={() => ConnectWallet()}>Connect Wallet</button>
        <div>{walletAddress ? walletAddress : "not connected"}</div>
        <button onClick={() => buy()}>Buy</button>
      </main>
    </>
  );
}
